development: &default
  adapter: postgresql
  database: docker_rails_example_development
  min_messages: WARNING
  pool: 5
  username: pguser
  password: pguser
  host: db

test:
  <<: *default
  database: docker_rails_example_development
